[package]
name = "scrypt-fuzz"
version = "0.0.0"
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
pbkdf2 = { version = "=0.13.0-pre.1", path = "../pbkdf2" }
salsa20 = { version = "=0.11.0-pre.2", default-features = false }
sha2 = { version = "=0.11.0-pre.4", default-features = false }
password-hash = { version = "0.6.0-rc.0", default-features = false, features = ["rand_core"], optional = true }
hex = "0.4"
base64 = "0.22.1"

[features]
default = ["simple", "std"]
simple = ["password-hash"]
std = ["password-hash/std"]

[dependencies.scrypt]
path = "../scrypt"

[[bin]]
name = "scrypt_fuzzer"
path = "fuzz_targets/scrypt_fuzzer.rs"
test = false
doc = false
bench = false
