name: fuzz-build

on:
  pull_request:
    paths:
      - ".github/workflows/fuzz_build.yml"
      - "fuzz/**"
      - "scrypt/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: fuzz

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    if: false # disabled while using pre-releases
    steps:
      - uses: actions/checkout@v4
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo build
