name: fuzz-build

on:
  pull_request:
    paths:
      - "fuzz/**"
  push:
    branches: master

defaults:
  run:
    working-directory: fuzz

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install cargo-fuzz
        run: |
          cargo install cargo-fuzz
      - name: Build with cargo-fuzz
        run: |
          cargo fuzz build -s none
