name: sha-crypt

on:
  pull_request:
    paths:
      - "sha-crypt/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: sha-crypt

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
# TODO(tarcieri): no_std
#  build:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        rust:
#          - 1.41.0 # MSRV
#          - stable
#        target:
#          - thumbv7em-none-eabi
#          - wasm32-unknown-unknown
#    steps:
#      - uses: actions/checkout@v1
#      - uses: actions-rs/toolchain@v1
#        with:
#          toolchain: ${{ matrix.rust }}
#          target: ${{ matrix.target }}
#          profile: minimal
#          override: true
#      - run: cargo build --release --target ${{ matrix.target }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.41.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
      - run: cargo test --release
      - run: cargo test --release --all-features
